### ISSUE TITLE
Visual bug while wearing the urchin costume

### ISSUE THREAD

**Issue by maxigaz** [AquariaOSE/Aquaria#35] opened 2016-07-19 19:20 UTC
In Aquaria OSE 1.002, there is a visual bug when I do the following:
1. Put on the urchin costume (represented as a spiky helmet in the menu). Now Naija should be in the normal form and she is not wearing a cape.
2. Switch to another form and switch back to normal _or_ go to another area.
3. Now a cape appears on Naija’s back, which has no textures and is completely white.

I’m on Manjaro Linux x64 and using the free AMD drivers.

Let me know if you need a save file and I'll attach it to my next comment.

**Comment by fgenesis** [comment] 2016-07-19 19:25
This problem is already fixed in the experimental branch and i also merged this specific change back into master (96206dd82a9de0f19b23be883396e51bd5f28907), but there hasn't been a release since then.
I'll leave the issue open until it's confirmed fixed in the next OSE release.

Thanks for the report tho!

**Closed** 2017-03-25 18:36 UTC
Labels: fixed for next release
